version: '3.3'

services:
  db:
    image: bitnami/mariadb:10.3-debian-10
    volumes:
      - db_data:/bitnami
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes

  web:
    container_name: opencart-30
    depends_on:
      - db
    build: .
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_HOST=db
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_USERNAME=admin
      - OPENCART_PASSWORD=admin
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
      - APACHE_HTTP_PORT_NUMBER=8000
      - APACHE_HTTPS_PORT_NUMBER=8443
    volumes:
      - web_data:/bitnami
      - ./assets/multistore.conf:/opt/bitnami/apache/conf/aliases/multistore.conf

volumes:
  db_data:
  web_data:
